package com.benhsoan.application.ucservice.user;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.time.Instant;
import java.util.Optional;
import java.util.UUID;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import com.benhsoan.domain.auditlog.AuditLog;
import com.benhsoan.domain.auth.User;
import com.benhsoan.domain.auth.exception.UserNotFoundException;
import com.benhsoan.domain.auth.exception.WeakPasswordException;
import com.benhsoan.port.dto.command.user.ResetPasswordCommand;
import com.benhsoan.port.dto.result.ResetPasswordResult;
import com.benhsoan.port.outbound.authSecurity.PasswordEncoderPort;
import com.benhsoan.port.outbound.repository.audit.AuditLogRepository;
import com.benhsoan.port.outbound.repository.auth.UserRepository;
import com.benhsoan.port.outbound.repository.auth.UserSessionRepository;
import com.benhsoan.port.outbound.security.CurrentUserPort;
import com.benhsoan.port.outbound.time.ClockPort;

@ExtendWith(MockitoExtension.class)
class ResetPasswordServiceTest {

    @Mock private UserRepository userRepository;
    @Mock private UserSessionRepository userSessionRepository;
    @Mock private PasswordEncoderPort passwordEncoderPort;
    @Mock private AuditLogRepository auditLogRepository;
    @Mock private CurrentUserPort currentUserPort;
    @Mock private ClockPort clockPort;

    private ResetPasswordService resetPasswordService;

    private final UUID adminId = UUID.randomUUID();
    private final UUID targetUserId = UUID.randomUUID();
    private final UUID roleId = UUID.randomUUID();
    private final Instant now = Instant.parse("2026-09-07T10:00:00Z");

    @BeforeEach
    void setUp() {
        resetPasswordService = new ResetPasswordService(
                userRepository,
                userSessionRepository,
                passwordEncoderPort,
                auditLogRepository,
                currentUserPort,
                clockPort
        );
    }

    private User createTargetUser() {
        return User.restore(
                targetUserId,
                "receptionist1",
                "$2a$10$oldHash",
                "Pham Mai Lan",
                "receptionist1@benhsoan.com",
                "0901000004",
                roleId,
                true,
                false,
                null,
                now
        );
    }

    @Test
    @DisplayName("throws UserNotFoundException when target user does not exist")
    void targetUserNotFoundThrowsException() {
        when(userRepository.findById(targetUserId)).thenReturn(Optional.empty());

        ResetPasswordCommand command = new ResetPasswordCommand(targetUserId, null);
        assertThrows(UserNotFoundException.class, () -> resetPasswordService.resetPassword(command));
    }

    @Test
    @DisplayName("throws WeakPasswordException when custom temporary password is weak")
    void weakCustomTempPasswordThrowsException() {
        User targetUser = createTargetUser();
        when(userRepository.findById(targetUserId)).thenReturn(Optional.of(targetUser));

        ResetPasswordCommand command = new ResetPasswordCommand(targetUserId, "123");
        assertThrows(WeakPasswordException.class, () -> resetPasswordService.resetPassword(command));
    }

    @Test
    @DisplayName("resets password with auto-generated temporary password and flags mustChangePassword (TC-03)")
    void resetPasswordWithAutoGeneratedTempPassword() {
        User targetUser = createTargetUser();
        when(userRepository.findById(targetUserId)).thenReturn(Optional.of(targetUser));
        when(passwordEncoderPort.encode(any())).thenReturn("$2a$10$tempHashedPassword");
        when(clockPort.now()).thenReturn(now);
        when(currentUserPort.getCurrentUserId()).thenReturn(adminId);

        ResetPasswordCommand command = new ResetPasswordCommand(targetUserId, null);
        ResetPasswordResult result = resetPasswordService.resetPassword(command);

        assertNotNull(result);
        assertEquals(targetUserId, result.userId());
        assertEquals("receptionist1", result.username());
        assertNotNull(result.temporaryPassword());
        assertTrue(result.temporaryPassword().length() >= 8);

        assertTrue(targetUser.isMustChangePassword());
        verify(userRepository).save(targetUser);
        verify(userSessionRepository).revokeByUserId(targetUserId, now);
        verify(auditLogRepository).save(any(AuditLog.class));
    }

    @Test
    @DisplayName("resets password with valid custom temporary password")
    void resetPasswordWithCustomTempPassword() {
        User targetUser = createTargetUser();
        when(userRepository.findById(targetUserId)).thenReturn(Optional.of(targetUser));
        when(passwordEncoderPort.encode("CustomTempPass123")).thenReturn("$2a$10$customHash");
        when(clockPort.now()).thenReturn(now);
        when(currentUserPort.getCurrentUserId()).thenReturn(adminId);

        ResetPasswordCommand command = new ResetPasswordCommand(targetUserId, "CustomTempPass123");
        ResetPasswordResult result = resetPasswordService.resetPassword(command);

        assertNotNull(result);
        assertEquals("CustomTempPass123", result.temporaryPassword());
        assertTrue(targetUser.isMustChangePassword());
        verify(userRepository).save(targetUser);
    }

    @Test
    @DisplayName("throws AccountDisabledException when target user is inactive (Finding 3 / ACCOUNT_DISABLED)")
    void inactiveTargetUserThrowsException() {
        User inactiveUser = User.restore(
                targetUserId,
                "receptionist1",
                "$2a$10$oldHash",
                "Pham Mai Lan",
                "receptionist1@benhsoan.com",
                "0901000004",
                roleId,
                false,
                false,
                null,
                now
        );
        when(userRepository.findById(targetUserId)).thenReturn(Optional.of(inactiveUser));

        ResetPasswordCommand command = new ResetPasswordCommand(targetUserId, null);
        assertThrows(com.benhsoan.domain.auth.exception.AccountDisabledException.class,
                () -> resetPasswordService.resetPassword(command));
        verify(userRepository, org.mockito.Mockito.never()).save(any());
        verify(userSessionRepository, org.mockito.Mockito.never()).revokeByUserId(any(), any());
    }
}
