-- =====================================================
-- V2__seed_auth_data.sql
-- Seed system roles, permission catalog and default accounts
-- =====================================================

INSERT INTO roles (id, name, description, is_system, created_at, updated_at)
VALUES
    (UUID_TO_BIN('11111111-1111-1111-1111-111111111111'), 'ADMIN', 'System administrator', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (UUID_TO_BIN('22222222-2222-2222-2222-222222222222'), 'DOCTOR', 'Doctor', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (UUID_TO_BIN('33333333-3333-3333-3333-333333333333'), 'NURSE', 'Nurse', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (UUID_TO_BIN('44444444-4444-4444-4444-444444444444'), 'RECEPTIONIST', 'Receptionist', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (UUID_TO_BIN('55555555-5555-5555-5555-555555555555'), 'PHARMACIST', 'Pharmacist', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (UUID_TO_BIN('66666666-6666-6666-6666-666666666666'), 'MANAGER', 'Clinic manager', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Permission codes are immutable contracts used by backend authorization.
INSERT INTO permissions (id, code, name, module, description, active, created_at, updated_at)
SELECT UUID_TO_BIN(UUID()), code, REPLACE(code, '_', ' '), module, NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM (
    SELECT 'USER_CREATE' AS code, 'USER' AS module UNION ALL
    SELECT 'USER_READ', 'USER' UNION ALL
    SELECT 'USER_UPDATE', 'USER' UNION ALL
    SELECT 'USER_DELETE', 'USER' UNION ALL
    SELECT 'USER_ASSIGN_ROLE', 'USER' UNION ALL
    SELECT 'ROLE_CREATE', 'ROLE' UNION ALL
    SELECT 'ROLE_READ', 'ROLE' UNION ALL
    SELECT 'ROLE_UPDATE', 'ROLE' UNION ALL
    SELECT 'ROLE_DELETE', 'ROLE' UNION ALL
    SELECT 'PERMISSION_READ', 'PERMISSION' UNION ALL
    SELECT 'PATIENT_CREATE', 'PATIENT' UNION ALL
    SELECT 'PATIENT_READ', 'PATIENT' UNION ALL
    SELECT 'PATIENT_UPDATE', 'PATIENT' UNION ALL
    SELECT 'PATIENT_DELETE', 'PATIENT' UNION ALL
    SELECT 'MEDICAL_RECORD_CREATE', 'MEDICAL_RECORD' UNION ALL
    SELECT 'MEDICAL_RECORD_READ', 'MEDICAL_RECORD' UNION ALL
    SELECT 'MEDICAL_RECORD_UPDATE', 'MEDICAL_RECORD' UNION ALL
    SELECT 'MEDICAL_RECORD_DELETE', 'MEDICAL_RECORD' UNION ALL
    SELECT 'MEDICAL_RECORD_UPDATE_STATUS', 'MEDICAL_RECORD' UNION ALL
    SELECT 'APPOINTMENT_CREATE', 'APPOINTMENT' UNION ALL
    SELECT 'APPOINTMENT_READ', 'APPOINTMENT' UNION ALL
    SELECT 'APPOINTMENT_UPDATE', 'APPOINTMENT' UNION ALL
    SELECT 'APPOINTMENT_DELETE', 'APPOINTMENT' UNION ALL
    SELECT 'PRESCRIPTION_CREATE', 'PRESCRIPTION' UNION ALL
    SELECT 'PRESCRIPTION_READ', 'PRESCRIPTION' UNION ALL
    SELECT 'PRESCRIPTION_UPDATE', 'PRESCRIPTION' UNION ALL
    SELECT 'PRESCRIPTION_DELETE', 'PRESCRIPTION' UNION ALL
    SELECT 'PRESCRIPTION_UPDATE_STATUS', 'PRESCRIPTION' UNION ALL
    SELECT 'PRESCRIPTION_PRINT', 'PRESCRIPTION' UNION ALL
    SELECT 'VITAL_SIGN_CREATE', 'VITAL_SIGN' UNION ALL
    SELECT 'VITAL_SIGN_READ', 'VITAL_SIGN' UNION ALL
    SELECT 'VITAL_SIGN_UPDATE', 'VITAL_SIGN' UNION ALL
    SELECT 'DIAGNOSIS_CREATE', 'DIAGNOSIS' UNION ALL
    SELECT 'DIAGNOSIS_READ', 'DIAGNOSIS' UNION ALL
    SELECT 'DIAGNOSIS_UPDATE', 'DIAGNOSIS' UNION ALL
    SELECT 'PHARMACY_CREATE', 'PHARMACY' UNION ALL
    SELECT 'PHARMACY_READ', 'PHARMACY' UNION ALL
    SELECT 'PHARMACY_UPDATE', 'PHARMACY' UNION ALL
    SELECT 'PHARMACY_DELETE', 'PHARMACY' UNION ALL
    SELECT 'INVOICE_CREATE', 'INVOICE' UNION ALL
    SELECT 'INVOICE_READ', 'INVOICE' UNION ALL
    SELECT 'INVOICE_UPDATE', 'INVOICE' UNION ALL
    SELECT 'INVOICE_DELETE', 'INVOICE' UNION ALL
    SELECT 'AUDIT_READ', 'AUDIT' UNION ALL
    SELECT 'REPORT_VIEW', 'REPORT' UNION ALL
    SELECT 'REPORT_EXPORT', 'REPORT' UNION ALL
    SELECT 'SERVICE_CATALOG_READ', 'SERVICE_CATALOG' UNION ALL
    SELECT 'SERVICE_CATALOG_CREATE', 'SERVICE_CATALOG' UNION ALL
    SELECT 'SERVICE_CATALOG_UPDATE', 'SERVICE_CATALOG' UNION ALL
    SELECT 'SERVICE_PRICE_MANAGE', 'SERVICE_CATALOG' UNION ALL
    SELECT 'QUEUE_CREATE', 'QUEUE' UNION ALL
    SELECT 'QUEUE_CALL_NEXT', 'QUEUE' UNION ALL
    SELECT 'QUEUE_UPDATE_STATUS', 'QUEUE' UNION ALL
    SELECT 'QUEUE_VIEW', 'QUEUE' UNION ALL
    SELECT 'QUEUE_COUNT', 'QUEUE' UNION ALL
    SELECT 'BACKUP_CREATE', 'BACKUP' UNION ALL
    SELECT 'BACKUP_READ', 'BACKUP' UNION ALL
    SELECT 'BACKUP_RESTORE', 'BACKUP' UNION ALL
    SELECT 'CLINIC_CONFIGURATION_READ', 'CLINIC_CONFIGURATION' UNION ALL
    SELECT 'CLINIC_CONFIGURATION_UPDATE', 'CLINIC_CONFIGURATION' UNION ALL
    SELECT 'ROOM_READ', 'ROOM' UNION ALL
    SELECT 'ROOM_CREATE', 'ROOM' UNION ALL
    SELECT 'ROOM_UPDATE', 'ROOM' UNION ALL
    SELECT 'ROOM_ASSIGNMENT_READ', 'ROOM' UNION ALL
    SELECT 'ROOM_ASSIGNMENT_UPDATE', 'ROOM' UNION ALL
    SELECT 'CLINICAL_ORDER_CREATE', 'CLINICAL_ORDER' UNION ALL
    SELECT 'CLINICAL_ORDER_READ', 'CLINICAL_ORDER' UNION ALL
    SELECT 'CLINICAL_RESULT_CREATE', 'CLINICAL_RESULT' UNION ALL
    SELECT 'CLINICAL_RESULT_READ', 'CLINICAL_RESULT' UNION ALL
    SELECT 'CLINICAL_RESULT_UPDATE', 'CLINICAL_RESULT' UNION ALL
    SELECT 'CLINICAL_RESULT_FINALIZE', 'CLINICAL_RESULT' UNION ALL
    SELECT 'CLINICAL_RESULT_ATTACHMENT_CREATE', 'CLINICAL_RESULT' UNION ALL
    SELECT 'CLINICAL_RESULT_ATTACHMENT_READ', 'CLINICAL_RESULT' UNION ALL
    SELECT 'CLINICAL_SERVICE_READ', 'CLINICAL_SERVICE' UNION ALL
    SELECT 'FOLLOW_UP_REMINDER_CREATE', 'FOLLOW_UP' UNION ALL
    SELECT 'FOLLOW_UP_REMINDER_READ', 'FOLLOW_UP' UNION ALL
    SELECT 'FOLLOW_UP_REMINDER_UPDATE', 'FOLLOW_UP' UNION ALL
    SELECT 'CARE_LOG_CREATE', 'CARE_LOG' UNION ALL
    SELECT 'CARE_LOG_READ', 'CARE_LOG' UNION ALL
    SELECT 'DASHBOARD_OPERATIONAL_READ', 'DASHBOARD'
) AS permission_catalog;

-- Preserve the existing ADMIN assignment from the former seed.
INSERT INTO role_permissions (role_id, permission_id)
SELECT UUID_TO_BIN('11111111-1111-1111-1111-111111111111'), id
FROM permissions
WHERE code NOT IN ('REPORT_VIEW', 'REPORT_EXPORT', 'PRESCRIPTION_PRINT');

INSERT INTO role_permissions (role_id, permission_id)
SELECT UUID_TO_BIN('22222222-2222-2222-2222-222222222222'), id
FROM permissions
WHERE code IN (
    'PATIENT_CREATE', 'PATIENT_READ', 'PATIENT_UPDATE',
    'MEDICAL_RECORD_CREATE', 'MEDICAL_RECORD_READ', 'MEDICAL_RECORD_UPDATE', 'MEDICAL_RECORD_UPDATE_STATUS',
    'PRESCRIPTION_CREATE', 'PRESCRIPTION_READ', 'PRESCRIPTION_UPDATE', 'PRESCRIPTION_DELETE', 'PRESCRIPTION_PRINT',
    'PHARMACY_READ',
    'DIAGNOSIS_CREATE', 'DIAGNOSIS_READ', 'DIAGNOSIS_UPDATE',
    'APPOINTMENT_READ',
    'CARE_LOG_CREATE', 'CARE_LOG_READ',
    'VITAL_SIGN_CREATE', 'VITAL_SIGN_READ', 'VITAL_SIGN_UPDATE',
    'QUEUE_CALL_NEXT', 'QUEUE_UPDATE_STATUS', 'QUEUE_VIEW', 'QUEUE_COUNT'
);

INSERT INTO role_permissions (role_id, permission_id)
SELECT UUID_TO_BIN('33333333-3333-3333-3333-333333333333'), id
FROM permissions
WHERE code IN (
    'PATIENT_READ', 'APPOINTMENT_READ',
    'VITAL_SIGN_CREATE', 'VITAL_SIGN_READ', 'VITAL_SIGN_UPDATE',
    'MEDICAL_RECORD_READ', 'MEDICAL_RECORD_UPDATE_STATUS',
    'QUEUE_UPDATE_STATUS', 'QUEUE_VIEW', 'QUEUE_COUNT'
);

INSERT INTO role_permissions (role_id, permission_id)
SELECT UUID_TO_BIN('44444444-4444-4444-4444-444444444444'), id
FROM permissions
WHERE code IN (
    'PATIENT_CREATE', 'PATIENT_READ', 'PATIENT_UPDATE',
    'APPOINTMENT_CREATE', 'APPOINTMENT_READ', 'APPOINTMENT_UPDATE', 'APPOINTMENT_DELETE',
    'INVOICE_CREATE', 'INVOICE_READ',
    'FOLLOW_UP_REMINDER_CREATE', 'FOLLOW_UP_REMINDER_READ', 'FOLLOW_UP_REMINDER_UPDATE',
    'CARE_LOG_CREATE', 'CARE_LOG_READ',
    'QUEUE_CREATE', 'QUEUE_VIEW', 'QUEUE_COUNT'
);

INSERT INTO role_permissions (role_id, permission_id)
SELECT UUID_TO_BIN('55555555-5555-5555-5555-555555555555'), id
FROM permissions
WHERE code IN (
    'PRESCRIPTION_READ', 'PRESCRIPTION_UPDATE_STATUS', 'PRESCRIPTION_PRINT',
    'PHARMACY_CREATE', 'PHARMACY_READ', 'PHARMACY_UPDATE',
    'QUEUE_VIEW', 'QUEUE_COUNT'
);

INSERT INTO role_permissions (role_id, permission_id)
SELECT UUID_TO_BIN('66666666-6666-6666-6666-666666666666'), id
FROM permissions
WHERE code IN (
    'INVOICE_READ', 'INVOICE_UPDATE', 'AUDIT_READ',
    'REPORT_VIEW', 'REPORT_EXPORT',
    'SERVICE_CATALOG_READ', 'SERVICE_CATALOG_CREATE', 'SERVICE_CATALOG_UPDATE', 'SERVICE_PRICE_MANAGE',
    'PATIENT_READ', 'QUEUE_VIEW', 'QUEUE_COUNT'
);

-- Default accounts share the existing administrator BCrypt hash.
INSERT INTO users (id, username, password_hash, full_name, email, phone, role_id, active, last_login_at, created_at)
VALUES
    (UUID_TO_BIN('00000000-0000-0000-0000-000000000000'), 'system', '$2a$10$OY5a1YZ/5Iaz2PcEKjfOveEyy3FVXm7ei9OxTW6jPMyap/Hlk.5sK', 'System', 'system@benhsoan.com', NULL, UUID_TO_BIN('11111111-1111-1111-1111-111111111111'), FALSE, NULL, CURRENT_TIMESTAMP),
    (UUID_TO_BIN('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1'), 'admin', '$2a$10$OY5a1YZ/5Iaz2PcEKjfOveEyy3FVXm7ei9OxTW6jPMyap/Hlk.5sK', 'System Administrator', 'admin@benhsoan.com', NULL, UUID_TO_BIN('11111111-1111-1111-1111-111111111111'), TRUE, NULL, CURRENT_TIMESTAMP),
    (UUID_TO_BIN('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2'), 'doctor1', '$2a$10$OY5a1YZ/5Iaz2PcEKjfOveEyy3FVXm7ei9OxTW6jPMyap/Hlk.5sK', 'Dr. Nguyen Minh Anh', 'doctor1@benhsoan.com', '0901000001', UUID_TO_BIN('22222222-2222-2222-2222-222222222222'), TRUE, NULL, CURRENT_TIMESTAMP),
    (UUID_TO_BIN('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3'), 'doctor2', '$2a$10$OY5a1YZ/5Iaz2PcEKjfOveEyy3FVXm7ei9OxTW6jPMyap/Hlk.5sK', 'Dr. Tran Quang Huy', 'doctor2@benhsoan.com', '0901000002', UUID_TO_BIN('22222222-2222-2222-2222-222222222222'), TRUE, NULL, CURRENT_TIMESTAMP),
    (UUID_TO_BIN('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa4'), 'nurse1', '$2a$10$OY5a1YZ/5Iaz2PcEKjfOveEyy3FVXm7ei9OxTW6jPMyap/Hlk.5sK', 'Le Thu Ha', 'nurse1@benhsoan.com', '0901000003', UUID_TO_BIN('33333333-3333-3333-3333-333333333333'), TRUE, NULL, CURRENT_TIMESTAMP),
    (UUID_TO_BIN('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa5'), 'receptionist1', '$2a$10$OY5a1YZ/5Iaz2PcEKjfOveEyy3FVXm7ei9OxTW6jPMyap/Hlk.5sK', 'Pham Mai Lan', 'receptionist1@benhsoan.com', '0901000004', UUID_TO_BIN('44444444-4444-4444-4444-444444444444'), TRUE, NULL, CURRENT_TIMESTAMP),
    (UUID_TO_BIN('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa6'), 'pharmacist1', '$2a$10$OY5a1YZ/5Iaz2PcEKjfOveEyy3FVXm7ei9OxTW6jPMyap/Hlk.5sK', 'Vo Thanh Nam', 'pharmacist1@benhsoan.com', '0901000005', UUID_TO_BIN('55555555-5555-5555-5555-555555555555'), TRUE, NULL, CURRENT_TIMESTAMP),
    (UUID_TO_BIN('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa7'), 'manager1', '$2a$10$OY5a1YZ/5Iaz2PcEKjfOveEyy3FVXm7ei9OxTW6jPMyap/Hlk.5sK', 'Clinic Manager', 'manager1@benhsoan.com', '0901000006', UUID_TO_BIN('66666666-6666-6666-6666-666666666666'), TRUE, NULL, CURRENT_TIMESTAMP);
