-- =====================================================
-- V2__seed_auth_data.sql
-- Seed system roles, comprehensive permission catalog,
-- role permission assignments, and default user accounts
-- =====================================================

-- ===========================
-- 1. Roles
-- ===========================
INSERT INTO roles (id, name, description, is_system, created_at, updated_at)
VALUES
    (UUID_TO_BIN('11111111-1111-1111-1111-111111111111'), 'ADMIN', 'System administrator', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (UUID_TO_BIN('22222222-2222-2222-2222-222222222222'), 'DOCTOR', 'Doctor', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (UUID_TO_BIN('44444444-4444-4444-4444-444444444444'), 'RECEPTIONIST', 'Receptionist', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (UUID_TO_BIN('55555555-5555-5555-5555-555555555555'), 'PHARMACIST', 'Pharmacist', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (UUID_TO_BIN('66666666-6666-6666-6666-666666666666'), 'MANAGER', 'Clinic manager', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (UUID_TO_BIN('77777777-7777-7777-7777-777777777777'), 'PATIENT', 'Patient portal account', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- ===========================
-- 2. Permissions Catalog (55 Permissions)
-- ===========================
INSERT INTO permissions (id, code, name, module, description, active, created_at, updated_at)
SELECT UUID_TO_BIN(UUID()), code, REPLACE(code, '_', ' '), module, NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM (
    -- User & Role
    SELECT 'USER_CREATE' AS code, 'USER' AS module UNION ALL
    SELECT 'USER_READ', 'USER' UNION ALL
    SELECT 'USER_UPDATE', 'USER' UNION ALL
    SELECT 'USER_DELETE', 'USER' UNION ALL
    SELECT 'USER_ASSIGN_ROLE', 'USER' UNION ALL
    SELECT 'USER_RESET_PASSWORD', 'USER' UNION ALL
    SELECT 'ROLE_CREATE', 'ROLE' UNION ALL
    SELECT 'ROLE_READ', 'ROLE' UNION ALL
    SELECT 'ROLE_UPDATE', 'ROLE' UNION ALL
    SELECT 'ROLE_DELETE', 'ROLE' UNION ALL
    SELECT 'PERMISSION_READ', 'PERMISSION' UNION ALL

    -- Patient & Consent & Allergy
    SELECT 'PATIENT_CREATE', 'PATIENT' UNION ALL
    SELECT 'PATIENT_READ', 'PATIENT' UNION ALL
    SELECT 'PATIENT_UPDATE', 'PATIENT' UNION ALL
    SELECT 'PATIENT_DELETE', 'PATIENT' UNION ALL
    SELECT 'PATIENT_CONSENT_READ', 'PATIENT_CONSENT' UNION ALL
    SELECT 'PATIENT_CONSENT_UPDATE', 'PATIENT_CONSENT' UNION ALL
    SELECT 'PATIENT_ALLERGY_READ', 'PATIENT_ALLERGY' UNION ALL
    SELECT 'PATIENT_ALLERGY_WRITE', 'PATIENT_ALLERGY' UNION ALL

    -- Medical Record & Diagnosis & Template
    SELECT 'MEDICAL_RECORD_CREATE', 'MEDICAL_RECORD' UNION ALL
    SELECT 'MEDICAL_RECORD_READ', 'MEDICAL_RECORD' UNION ALL
    SELECT 'MEDICAL_RECORD_UPDATE', 'MEDICAL_RECORD' UNION ALL
    SELECT 'MEDICAL_RECORD_DELETE', 'MEDICAL_RECORD' UNION ALL
    SELECT 'MEDICAL_RECORD_UPDATE_STATUS', 'MEDICAL_RECORD' UNION ALL
    SELECT 'MEDICAL_RECORD_COPY', 'MEDICAL_RECORD' UNION ALL
    SELECT 'MEDICAL_RECORD_VERSION_HISTORY_READ', 'MEDICAL_RECORD' UNION ALL
    SELECT 'MEDICAL_RECORD_TEMPLATE_MANAGE', 'MEDICAL_RECORD_TEMPLATE' UNION ALL
    SELECT 'VITAL_SIGN_CREATE', 'VITAL_SIGN' UNION ALL
    SELECT 'VITAL_SIGN_READ', 'VITAL_SIGN' UNION ALL
    SELECT 'VITAL_SIGN_UPDATE', 'VITAL_SIGN' UNION ALL
    SELECT 'DIAGNOSIS_CREATE', 'DIAGNOSIS' UNION ALL
    SELECT 'DIAGNOSIS_READ', 'DIAGNOSIS' UNION ALL
    SELECT 'DIAGNOSIS_UPDATE', 'DIAGNOSIS' UNION ALL
    SELECT 'DIAGNOSIS_CATALOG_MANAGE', 'DIAGNOSIS_CATALOG' UNION ALL

    -- Appointment & Queue & Scheduling
    SELECT 'APPOINTMENT_CREATE', 'APPOINTMENT' UNION ALL
    SELECT 'APPOINTMENT_READ', 'APPOINTMENT' UNION ALL
    SELECT 'APPOINTMENT_UPDATE', 'APPOINTMENT' UNION ALL
    SELECT 'APPOINTMENT_DELETE', 'APPOINTMENT' UNION ALL
    SELECT 'QUEUE_CREATE', 'QUEUE' UNION ALL
    SELECT 'QUEUE_CALL_NEXT', 'QUEUE' UNION ALL
    SELECT 'QUEUE_UPDATE_STATUS', 'QUEUE' UNION ALL
    SELECT 'QUEUE_VIEW', 'QUEUE' UNION ALL
    SELECT 'QUEUE_COUNT', 'QUEUE' UNION ALL
    SELECT 'ROOM_READ', 'ROOM' UNION ALL
    SELECT 'ROOM_CREATE', 'ROOM' UNION ALL
    SELECT 'ROOM_UPDATE', 'ROOM' UNION ALL
    SELECT 'ROOM_ASSIGNMENT_READ', 'ROOM' UNION ALL
    SELECT 'ROOM_ASSIGNMENT_UPDATE', 'ROOM' UNION ALL
    SELECT 'DOCTOR_SCHEDULE_READ', 'DOCTOR_SCHEDULE' UNION ALL
    SELECT 'DOCTOR_SCHEDULE_UPDATE', 'DOCTOR_SCHEDULE' UNION ALL
    SELECT 'DOCTOR_TIMEOFF_READ', 'DOCTOR_SCHEDULE' UNION ALL
    SELECT 'DOCTOR_TIMEOFF_CREATE', 'DOCTOR_SCHEDULE' UNION ALL
    SELECT 'DOCTOR_TIMEOFF_CANCEL', 'DOCTOR_SCHEDULE' UNION ALL

    -- Prescription & Pharmacy & Interconnection
    SELECT 'PRESCRIPTION_CREATE', 'PRESCRIPTION' UNION ALL
    SELECT 'PRESCRIPTION_READ', 'PRESCRIPTION' UNION ALL
    SELECT 'PRESCRIPTION_UPDATE', 'PRESCRIPTION' UNION ALL
    SELECT 'PRESCRIPTION_DELETE', 'PRESCRIPTION' UNION ALL
    SELECT 'PRESCRIPTION_UPDATE_STATUS', 'PRESCRIPTION' UNION ALL
    SELECT 'PRESCRIPTION_PRINT', 'PRESCRIPTION' UNION ALL
    SELECT 'PRESCRIPTION_ALLERGY_WARNING_VIEW', 'PRESCRIPTION_ALLERGY_WARNING' UNION ALL
    SELECT 'PRESCRIPTION_INTERCONNECTION_READ', 'PRESCRIPTION_INTERCONNECTION' UNION ALL
    SELECT 'PRESCRIPTION_INTERCONNECTION_SEND', 'PRESCRIPTION_INTERCONNECTION' UNION ALL
    SELECT 'PRESCRIPTION_INTERCONNECTION_RETRY', 'PRESCRIPTION_INTERCONNECTION' UNION ALL
    SELECT 'PHARMACY_CREATE', 'PHARMACY' UNION ALL
    SELECT 'PHARMACY_READ', 'PHARMACY' UNION ALL
    SELECT 'PHARMACY_UPDATE', 'PHARMACY' UNION ALL
    SELECT 'PHARMACY_DELETE', 'PHARMACY' UNION ALL

    -- Clinical Orders & Results
    SELECT 'CLINICAL_ORDER_CREATE', 'CLINICAL_ORDER' UNION ALL
    SELECT 'CLINICAL_ORDER_READ', 'CLINICAL_ORDER' UNION ALL
    SELECT 'CLINICAL_RESULT_CREATE', 'CLINICAL_RESULT' UNION ALL
    SELECT 'CLINICAL_RESULT_READ', 'CLINICAL_RESULT' UNION ALL
    SELECT 'CLINICAL_RESULT_UPDATE', 'CLINICAL_RESULT' UNION ALL
    SELECT 'CLINICAL_RESULT_FINALIZE', 'CLINICAL_RESULT' UNION ALL
    SELECT 'CLINICAL_RESULT_ATTACHMENT_CREATE', 'CLINICAL_RESULT' UNION ALL
    SELECT 'CLINICAL_RESULT_ATTACHMENT_READ', 'CLINICAL_RESULT' UNION ALL
    SELECT 'CLINICAL_SERVICE_READ', 'CLINICAL_SERVICE' UNION ALL

    -- Billing & Invoices
    SELECT 'INVOICE_CREATE', 'INVOICE' UNION ALL
    SELECT 'INVOICE_READ', 'INVOICE' UNION ALL
    SELECT 'INVOICE_UPDATE', 'INVOICE' UNION ALL
    SELECT 'INVOICE_DELETE', 'INVOICE' UNION ALL

    -- Reports & Dashboard & Audit & Security
    SELECT 'AUDIT_READ', 'AUDIT' UNION ALL
    SELECT 'ACCESS_LOG_REPORT_EXPORT', 'AUDIT' UNION ALL
    SELECT 'REPORT_VIEW', 'REPORT' UNION ALL
    SELECT 'REPORT_EXPORT', 'REPORT' UNION ALL
    SELECT 'DASHBOARD_OPERATIONAL_READ', 'DASHBOARD' UNION ALL
    SELECT 'SECURITY_ALERT_VIEW', 'SECURITY_ALERT' UNION ALL

    -- Service Catalog
    SELECT 'SERVICE_CATALOG_READ', 'SERVICE_CATALOG' UNION ALL
    SELECT 'SERVICE_CATALOG_CREATE', 'SERVICE_CATALOG' UNION ALL
    SELECT 'SERVICE_CATALOG_UPDATE', 'SERVICE_CATALOG' UNION ALL
    SELECT 'SERVICE_PRICE_MANAGE', 'SERVICE_CATALOG' UNION ALL

    -- System & Config & Backup & Follow-up
    SELECT 'BACKUP_CREATE', 'BACKUP' UNION ALL
    SELECT 'BACKUP_READ', 'BACKUP' UNION ALL
    SELECT 'BACKUP_RESTORE', 'BACKUP' UNION ALL
    SELECT 'CLINIC_CONFIGURATION_READ', 'CLINIC_CONFIGURATION' UNION ALL
    SELECT 'CLINIC_CONFIGURATION_UPDATE', 'CLINIC_CONFIGURATION' UNION ALL
    SELECT 'SYSTEM_CONFIG_READ', 'SYSTEM_CONFIG' UNION ALL
    SELECT 'SYSTEM_CONFIG_UPDATE', 'SYSTEM_CONFIG' UNION ALL
    SELECT 'FOLLOW_UP_REMINDER_CREATE', 'FOLLOW_UP' UNION ALL
    SELECT 'FOLLOW_UP_REMINDER_READ', 'FOLLOW_UP' UNION ALL
    SELECT 'FOLLOW_UP_REMINDER_UPDATE', 'FOLLOW_UP' UNION ALL
    SELECT 'CARE_LOG_CREATE', 'CARE_LOG' UNION ALL
    SELECT 'CARE_LOG_READ', 'CARE_LOG'
) AS permission_catalog;

-- ===========================
-- 3. Role Permission Assignments
-- ===========================

-- 3.1 ADMIN (Toàn quyền hệ thống, trừ in đơn thuốc trực tiếp & xem báo cáo y khoa riêng)
INSERT INTO role_permissions (role_id, permission_id)
SELECT UUID_TO_BIN('11111111-1111-1111-1111-111111111111'), id
FROM permissions
WHERE code NOT IN ('REPORT_VIEW', 'REPORT_EXPORT', 'PRESCRIPTION_PRINT');

-- 3.2 DOCTOR
INSERT INTO role_permissions (role_id, permission_id)
SELECT UUID_TO_BIN('22222222-2222-2222-2222-222222222222'), id
FROM permissions
WHERE code IN (
    'PATIENT_CREATE', 'PATIENT_READ', 'PATIENT_UPDATE',
    'PATIENT_ALLERGY_READ', 'PATIENT_ALLERGY_WRITE',
    'MEDICAL_RECORD_CREATE', 'MEDICAL_RECORD_READ', 'MEDICAL_RECORD_UPDATE', 'MEDICAL_RECORD_UPDATE_STATUS',
    'MEDICAL_RECORD_COPY', 'MEDICAL_RECORD_VERSION_HISTORY_READ',
    'PRESCRIPTION_CREATE', 'PRESCRIPTION_READ', 'PRESCRIPTION_UPDATE', 'PRESCRIPTION_DELETE', 'PRESCRIPTION_PRINT',
    'PRESCRIPTION_ALLERGY_WARNING_VIEW',
    'PRESCRIPTION_INTERCONNECTION_READ', 'PRESCRIPTION_INTERCONNECTION_SEND', 'PRESCRIPTION_INTERCONNECTION_RETRY',
    'PHARMACY_READ',
    'DIAGNOSIS_CREATE', 'DIAGNOSIS_READ', 'DIAGNOSIS_UPDATE',
    'APPOINTMENT_READ',
    'CARE_LOG_CREATE', 'CARE_LOG_READ',
    'VITAL_SIGN_CREATE', 'VITAL_SIGN_READ', 'VITAL_SIGN_UPDATE',
    'QUEUE_CALL_NEXT', 'QUEUE_UPDATE_STATUS', 'QUEUE_VIEW', 'QUEUE_COUNT',
    'CLINICAL_ORDER_CREATE', 'CLINICAL_ORDER_READ',
    'CLINICAL_RESULT_CREATE', 'CLINICAL_RESULT_UPDATE', 'CLINICAL_RESULT_FINALIZE', 'CLINICAL_RESULT_READ',
    'CLINICAL_RESULT_ATTACHMENT_CREATE', 'CLINICAL_RESULT_ATTACHMENT_READ',
    'CLINICAL_SERVICE_READ', 'ROOM_READ', 'ROOM_ASSIGNMENT_READ',
    'DOCTOR_SCHEDULE_READ', 'DOCTOR_TIMEOFF_READ', 'DOCTOR_TIMEOFF_CREATE', 'DOCTOR_TIMEOFF_CANCEL'
);

-- 3.3 RECEPTIONIST
INSERT INTO role_permissions (role_id, permission_id)
SELECT UUID_TO_BIN('44444444-4444-4444-4444-444444444444'), id
FROM permissions
WHERE code IN (
    'PATIENT_CREATE', 'PATIENT_READ', 'PATIENT_UPDATE',
    'PATIENT_CONSENT_READ', 'PATIENT_CONSENT_UPDATE',
    'APPOINTMENT_CREATE', 'APPOINTMENT_READ', 'APPOINTMENT_UPDATE', 'APPOINTMENT_DELETE',
    'INVOICE_CREATE', 'INVOICE_READ',
    'FOLLOW_UP_REMINDER_CREATE', 'FOLLOW_UP_REMINDER_READ', 'FOLLOW_UP_REMINDER_UPDATE',
    'CARE_LOG_CREATE', 'CARE_LOG_READ',
    'QUEUE_CREATE', 'QUEUE_VIEW', 'QUEUE_COUNT', 'QUEUE_UPDATE_STATUS',
    'ROOM_READ', 'ROOM_ASSIGNMENT_READ', 'USER_READ',
    'DOCTOR_SCHEDULE_READ'
);

-- 3.4 PHARMACIST
INSERT INTO role_permissions (role_id, permission_id)
SELECT UUID_TO_BIN('55555555-5555-5555-5555-555555555555'), id
FROM permissions
WHERE code IN (
    'PRESCRIPTION_READ', 'PRESCRIPTION_UPDATE_STATUS', 'PRESCRIPTION_PRINT',
    'PRESCRIPTION_INTERCONNECTION_READ',
    'PHARMACY_CREATE', 'PHARMACY_READ', 'PHARMACY_UPDATE',
    'PATIENT_ALLERGY_READ',
    'QUEUE_VIEW', 'QUEUE_COUNT'
);

-- 3.5 MANAGER
INSERT INTO role_permissions (role_id, permission_id)
SELECT UUID_TO_BIN('66666666-6666-6666-6666-666666666666'), id
FROM permissions
WHERE code IN (
    'USER_READ',
    'INVOICE_READ', 'INVOICE_UPDATE',
    'AUDIT_READ', 'ACCESS_LOG_REPORT_EXPORT',
    'REPORT_VIEW', 'REPORT_EXPORT',
    'SERVICE_CATALOG_READ', 'SERVICE_CATALOG_CREATE', 'SERVICE_CATALOG_UPDATE', 'SERVICE_PRICE_MANAGE',
    'PATIENT_READ', 'QUEUE_VIEW', 'QUEUE_COUNT',
    'DASHBOARD_OPERATIONAL_READ', 'APPOINTMENT_READ',
    'MEDICAL_RECORD_READ', 'MEDICAL_RECORD_COPY', 'MEDICAL_RECORD_VERSION_HISTORY_READ',
    'MEDICAL_RECORD_TEMPLATE_MANAGE',
    'DOCTOR_SCHEDULE_READ', 'DOCTOR_SCHEDULE_UPDATE', 'DOCTOR_TIMEOFF_READ', 'DOCTOR_TIMEOFF_CREATE', 'DOCTOR_TIMEOFF_CANCEL',
    'ROOM_READ', 'ROOM_ASSIGNMENT_READ',
    'CLINIC_CONFIGURATION_READ', 'CLINIC_CONFIGURATION_UPDATE'
);

-- 3.6 PATIENT: Truy cập được kiểm soát ở runtime qua PatientAccessGuard, không cần gán permission nội bộ.

-- ===========================
-- 4. Default Accounts (Password: Password123@ / BCrypt hash)
-- ===========================
INSERT INTO users (id, username, password_hash, full_name, email, phone, role_id, active, must_change_password, last_login_at, created_at)
VALUES
    -- System internal
    (UUID_TO_BIN('00000000-0000-0000-0000-000000000000'), 'system', '$2a$10$OY5a1YZ/5Iaz2PcEKjfOveEyy3FVXm7ei9OxTW6jPMyap/Hlk.5sK', 'System', 'system@benhsoan.com', NULL, UUID_TO_BIN('11111111-1111-1111-1111-111111111111'), FALSE, FALSE, NULL, CURRENT_TIMESTAMP),
    -- Administrator
    (UUID_TO_BIN('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1'), 'admin', '$2a$10$OY5a1YZ/5Iaz2PcEKjfOveEyy3FVXm7ei9OxTW6jPMyap/Hlk.5sK', 'System Administrator', 'admin@benhsoan.com', '0901000000', UUID_TO_BIN('11111111-1111-1111-1111-111111111111'), TRUE, FALSE, NULL, CURRENT_TIMESTAMP),
    -- Doctors
    (UUID_TO_BIN('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2'), 'doctor1', '$2a$10$OY5a1YZ/5Iaz2PcEKjfOveEyy3FVXm7ei9OxTW6jPMyap/Hlk.5sK', 'Dr. Nguyen Minh Anh', 'doctor1@benhsoan.com', '0901000001', UUID_TO_BIN('22222222-2222-2222-2222-222222222222'), TRUE, FALSE, NULL, CURRENT_TIMESTAMP),
    (UUID_TO_BIN('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3'), 'doctor2', '$2a$10$OY5a1YZ/5Iaz2PcEKjfOveEyy3FVXm7ei9OxTW6jPMyap/Hlk.5sK', 'Dr. Tran Quang Huy', 'doctor2@benhsoan.com', '0901000002', UUID_TO_BIN('22222222-2222-2222-2222-222222222222'), TRUE, FALSE, NULL, CURRENT_TIMESTAMP),
    -- Receptionist
    (UUID_TO_BIN('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa5'), 'receptionist1', '$2a$10$OY5a1YZ/5Iaz2PcEKjfOveEyy3FVXm7ei9OxTW6jPMyap/Hlk.5sK', 'Pham Mai Lan', 'receptionist1@benhsoan.com', '0901000004', UUID_TO_BIN('44444444-4444-4444-4444-444444444444'), TRUE, FALSE, NULL, CURRENT_TIMESTAMP),
    -- Pharmacist
    (UUID_TO_BIN('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa6'), 'pharmacist1', '$2a$10$OY5a1YZ/5Iaz2PcEKjfOveEyy3FVXm7ei9OxTW6jPMyap/Hlk.5sK', 'Vo Thanh Nam', 'pharmacist1@benhsoan.com', '0901000005', UUID_TO_BIN('55555555-5555-5555-5555-555555555555'), TRUE, FALSE, NULL, CURRENT_TIMESTAMP),
    -- Clinic Manager
    (UUID_TO_BIN('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa7'), 'manager1', '$2a$10$OY5a1YZ/5Iaz2PcEKjfOveEyy3FVXm7ei9OxTW6jPMyap/Hlk.5sK', 'Clinic Manager', 'manager1@benhsoan.com', '0901000006', UUID_TO_BIN('66666666-6666-6666-6666-666666666666'), TRUE, FALSE, NULL, CURRENT_TIMESTAMP),
    -- Patient Portal Accounts (Linked to BN000001, BN000002) -> Demo Epic NCL-14
    (UUID_TO_BIN('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa11'), 'patient1', '$2a$10$OY5a1YZ/5Iaz2PcEKjfOveEyy3FVXm7ei9OxTW6jPMyap/Hlk.5sK', 'Nguyen Van An', 'an@example.com', '0910000001', UUID_TO_BIN('77777777-7777-7777-7777-777777777777'), TRUE, FALSE, NULL, CURRENT_TIMESTAMP),
    (UUID_TO_BIN('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa12'), 'patient2', '$2a$10$OY5a1YZ/5Iaz2PcEKjfOveEyy3FVXm7ei9OxTW6jPMyap/Hlk.5sK', 'Tran Thi Binh', 'binh@example.com', '0910000002', UUID_TO_BIN('77777777-7777-7777-7777-777777777777'), TRUE, FALSE, NULL, CURRENT_TIMESTAMP),
    -- Locked Staff Account -> Demo US-04
    (UUID_TO_BIN('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa13'), 'locked_staff', '$2a$10$OY5a1YZ/5Iaz2PcEKjfOveEyy3FVXm7ei9OxTW6jPMyap/Hlk.5sK', 'Nhan Vien Khoa', 'locked@benhsoan.com', '0901000099', UUID_TO_BIN('44444444-4444-4444-4444-444444444444'), FALSE, FALSE, NULL, CURRENT_TIMESTAMP),
    -- Force Change Password Account -> Demo US-72
    (UUID_TO_BIN('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa14'), 'doctor_new', '$2a$10$OY5a1YZ/5Iaz2PcEKjfOveEyy3FVXm7ei9OxTW6jPMyap/Hlk.5sK', 'Dr. Le Hoang Nam', 'doctor_new@benhsoan.com', '0901000098', UUID_TO_BIN('22222222-2222-2222-2222-222222222222'), TRUE, TRUE, NULL, CURRENT_TIMESTAMP);

-- ===========================
-- 5. Seed Login Attempts (Demo US-78: Brute-Force & Temporary Lockout)
-- ===========================
INSERT INTO login_attempts (identifier, attempts, blocked_until, updated_at)
VALUES
    -- 1. Warning attempt (2 failed attempts, not yet locked)
    ('receptionist1', 2, NULL, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 5 MINUTE)),
    -- 2. Lockout attempt (5 failed attempts, locked for 15 minutes)
    ('doctor2', 5, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 15 MINUTE), CURRENT_TIMESTAMP);
