INSERT INTO appointments (id, appointment_code, patient_id, doctor_id, start_time, end_time, status, reason, cancel_reason, checked_in_at, completed_at, created_by, created_at) VALUES
(UUID_TO_BIN('cccccccc-cccc-cccc-cccc-ccccccccc001'), 'LH000001', UUID_TO_BIN('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbb001'), UUID_TO_BIN('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2'), DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 30 MINUTE), DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 MINUTE), 'SCHEDULED', 'Kham tong quat qua han', NULL, NULL, NULL, UUID_TO_BIN('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa5'), CURRENT_TIMESTAMP),
(UUID_TO_BIN('cccccccc-cccc-cccc-cccc-ccccccccc002'), 'LH000002', UUID_TO_BIN('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbb002'), UUID_TO_BIN('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2'), DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1470 MINUTE), 'SCHEDULED', 'Tai kham noi khoa', NULL, NULL, NULL, UUID_TO_BIN('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa5'), CURRENT_TIMESTAMP),
(UUID_TO_BIN('cccccccc-cccc-cccc-cccc-ccccccccc003'), 'LH000003', UUID_TO_BIN('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbb003'), UUID_TO_BIN('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3'), DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2910 MINUTE), 'SCHEDULED', 'Kham chuyen khoa', NULL, NULL, NULL, UUID_TO_BIN('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa5'), CURRENT_TIMESTAMP),
(UUID_TO_BIN('cccccccc-cccc-cccc-cccc-ccccccccc004'), 'LH000004', UUID_TO_BIN('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbb004'), UUID_TO_BIN('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2'), DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY), DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 4290 MINUTE), 'COMPLETED', 'Kham da hoan tat', NULL, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY), DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY), UUID_TO_BIN('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa5'), CURRENT_TIMESTAMP),
(UUID_TO_BIN('cccccccc-cccc-cccc-cccc-ccccccccc005'), 'LH000005', UUID_TO_BIN('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbb005'), UUID_TO_BIN('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3'), DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY), DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2850 MINUTE), 'NO_SHOW', 'Benh nhan vang mat', NULL, NULL, NULL, UUID_TO_BIN('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa5'), CURRENT_TIMESTAMP),
(UUID_TO_BIN('cccccccc-cccc-cccc-cccc-ccccccccc006'), 'LH000006', UUID_TO_BIN('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbb006'), UUID_TO_BIN('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2'), DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 3 DAY), DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 4350 MINUTE), 'CANCELLED', 'Lich da huy', 'Benh nhan ban', NULL, NULL, UUID_TO_BIN('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa5'), CURRENT_TIMESTAMP);


INSERT INTO rooms (id, room_code, room_name, active, created_at, updated_at) VALUES
(UUID_TO_BIN('90000000-0000-0000-0000-000000000001'), 'P101', 'Phong kham 101', TRUE, CURRENT_TIMESTAMP, NULL),
(UUID_TO_BIN('90000000-0000-0000-0000-000000000002'), 'P102', 'Phong kham 102', TRUE, CURRENT_TIMESTAMP, NULL);

INSERT INTO doctor_room_assignments (id, doctor_id, room_id, assigned_by, assigned_at) VALUES
(UUID_TO_BIN('91000000-0000-0000-0000-000000000001'), UUID_TO_BIN('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2'), UUID_TO_BIN('90000000-0000-0000-0000-000000000001'), UUID_TO_BIN('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1'), CURRENT_TIMESTAMP),
(UUID_TO_BIN('91000000-0000-0000-0000-000000000002'), UUID_TO_BIN('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3'), UUID_TO_BIN('90000000-0000-0000-0000-000000000002'), UUID_TO_BIN('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1'), CURRENT_TIMESTAMP);
