package com.benhsoan.persistence.adapterRepository.prescription;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;

import com.benhsoan.domain.prescription.enums.InterconnectionStatus;
import com.benhsoan.domain.prescription.enums.PrescriptionReconciliationOutcome;
import com.benhsoan.domain.prescription.enums.PrescriptionStatus;
import com.benhsoan.persistence.entity.prescription.PrescriptionDispenseItemEntity;
import com.benhsoan.persistence.entity.prescription.PrescriptionEntity;
import com.benhsoan.persistence.entity.prescription.PrescriptionReconciliationNoteEntity;
import com.benhsoan.persistence.jpaRepository.prescription.JpaPrescriptionDispenseItemRepository;
import com.benhsoan.persistence.jpaRepository.prescription.JpaPrescriptionReconciliationNoteRepository;
import com.benhsoan.port.dto.query.prescription.ReconciliationOutcomeGroup;
import com.benhsoan.port.dto.query.prescription.ReconciliationQueryFilter;
import com.benhsoan.port.dto.result.PrescriptionReconciliationItemResult;

import jakarta.persistence.EntityManager;

/**
 * NCL-12-CN-007 CV-02 query behaviour on H2.
 *
 * Flyway is disabled for this slice test on purpose: the MySQL migrations cannot run on H2
 * (see the project convention used by the other query-repository integration tests), so the
 * schema is generated by Hibernate and the JPQL projection itself is what gets exercised.
 */
@DataJpaTest(properties = {
        "spring.flyway.enabled=false",
        "spring.sql.init.mode=never",
        "spring.datasource.url=jdbc:h2:mem:reconciliation-test;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE",
        "spring.jpa.database-platform=org.hibernate.dialect.H2Dialect",
        "spring.jpa.hibernate.ddl-auto=create-drop"
})
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.ANY)
@DisplayName("PrescriptionReconciliationQueryRepositoryAdapter - H2")
class PrescriptionReconciliationQueryRepositoryAdapterIntegrationTest {

    private static final Instant PERIOD_FROM = Instant.parse("2026-09-01T00:00:00Z");

    private static final Instant PERIOD_TO = Instant.parse("2026-10-01T00:00:00Z");

    @Autowired
    private EntityManager entityManager;

    @Autowired
    private JpaPrescriptionDispenseItemRepository dispenseItemRepository;

    @Autowired
    private JpaPrescriptionReconciliationNoteRepository noteRepository;

    private PrescriptionReconciliationQueryRepositoryAdapter adapter;

    @BeforeEach
    void setUp() {
        adapter = new PrescriptionReconciliationQueryRepositoryAdapter(
                entityManager, dispenseItemRepository, noteRepository);
    }

    private UUID persistPrescription(
            String code,
            PrescriptionStatus status,
            InterconnectionStatus interconnectionStatus,
            Instant prescribedAt,
            Instant interconnectedAt
    ) {
        UUID id = UUID.randomUUID();
        entityManager.persist(PrescriptionEntity.builder()
                .id(id)
                .prescriptionCode(code)
                .medicalRecordId(UUID.randomUUID())
                .status(status)
                .prescribedBy(UUID.randomUUID())
                .prescribedAt(prescribedAt)
                .interconnectionStatus(interconnectionStatus)
                .lastInterconnectionAt(interconnectedAt)
                .lastInterconnectionError(interconnectionStatus == InterconnectionStatus.FAILED
                        ? "gateway timeout"
                        : null)
                .interconnectionReceiptCode(interconnectionStatus == InterconnectionStatus.SUCCESS
                        ? "LT-" + code
                        : null)
                .build());
        return id;
    }

    private void persistDispense(UUID prescriptionId, Instant dispensedAt) {
        entityManager.persist(PrescriptionDispenseItemEntity.builder()
                .id(UUID.randomUUID())
                .prescriptionId(prescriptionId)
                .prescriptionItemId(UUID.randomUUID())
                .medicineId(UUID.randomUUID())
                .medicineBatchId(UUID.randomUUID())
                .dispensedQuantity(1)
                .returnedQuantity(0)
                .dispensedBy(UUID.randomUUID())
                .dispensedAt(dispensedAt)
                .createdAt(dispensedAt)
                .build());
    }

    private void flush() {
        entityManager.flush();
        entityManager.clear();
    }

    private static ReconciliationQueryFilter filter(
            Instant from,
            Instant to,
            String prescriptionCode,
            ReconciliationOutcomeGroup... groups
    ) {
        return new ReconciliationQueryFilter(from, to, prescriptionCode, List.of(groups));
    }

    private Page<PrescriptionReconciliationItemResult> search(ReconciliationQueryFilter filter) {
        return adapter.findByFilter(filter, PageRequest.of(0, 20));
    }

    @Test
    void prescriptionIssuedInsideThePeriodIsReturned() {
        persistPrescription("RX000001", PrescriptionStatus.PENDING_DISPENSE,
                InterconnectionStatus.SUCCESS, PERIOD_FROM.plusSeconds(3600), PERIOD_FROM.plusSeconds(7200));
        flush();

        Page<PrescriptionReconciliationItemResult> page = search(
                filter(PERIOD_FROM, PERIOD_TO, null));

        assertEquals(1, page.getTotalElements());
        assertEquals("RX000001", page.getContent().get(0).prescriptionCode());
    }

    @Test
    void outOfPeriodPrescriptionIsExcluded() {
        persistPrescription("RX000002", PrescriptionStatus.PENDING_DISPENSE,
                InterconnectionStatus.NOT_SENT, PERIOD_TO.plusSeconds(86400), null);
        flush();

        assertEquals(0, search(filter(PERIOD_FROM, PERIOD_TO, null)).getTotalElements());
    }

    @Test
    void periodIsHalfOpenAtBothBounds() {
        persistPrescription("RX000003", PrescriptionStatus.PENDING_DISPENSE,
                InterconnectionStatus.NOT_SENT, PERIOD_FROM, null);
        persistPrescription("RX000004", PrescriptionStatus.PENDING_DISPENSE,
                InterconnectionStatus.NOT_SENT, PERIOD_TO, null);
        flush();

        Page<PrescriptionReconciliationItemResult> page = search(
                filter(PERIOD_FROM, PERIOD_TO, null));

        assertEquals(1, page.getTotalElements());
        assertEquals("RX000003", page.getContent().get(0).prescriptionCode());
    }

    @Test
    void transmissionInsideThePeriodPullsInAnOlderPrescription() {
        persistPrescription("RX000005", PrescriptionStatus.PENDING_DISPENSE,
                InterconnectionStatus.FAILED, PERIOD_FROM.minusSeconds(86400 * 30), PERIOD_FROM.plusSeconds(60));
        flush();

        assertEquals(1, search(filter(PERIOD_FROM, PERIOD_TO, null)).getTotalElements());
    }

    @Test
    void dispensingInsideThePeriodPullsInAPrescriptionThatWasNeverTransmitted() {
        UUID id = persistPrescription("RX000006", PrescriptionStatus.DISPENSED,
                InterconnectionStatus.NOT_SENT, PERIOD_FROM.minusSeconds(86400 * 30), null);
        persistDispense(id, PERIOD_FROM.plusSeconds(3600));
        flush();

        Page<PrescriptionReconciliationItemResult> page = search(
                filter(PERIOD_FROM, PERIOD_TO, null));

        assertEquals(1, page.getTotalElements());
        PrescriptionReconciliationItemResult row = page.getContent().get(0);
        assertEquals(PrescriptionReconciliationOutcome.DISPENSED_NOT_TRANSMITTED, row.outcome());
        assertTrue(row.discrepancy());
        assertFalse(row.retransmissionEligible());
        assertNull(row.lastInterconnectionAt());
    }

    @Test
    void unboundedPeriodReturnsEverything() {
        persistPrescription("RX000007", PrescriptionStatus.PENDING_DISPENSE,
                InterconnectionStatus.NOT_SENT, PERIOD_FROM.minusSeconds(86400 * 400), null);
        persistPrescription("RX000008", PrescriptionStatus.PENDING_DISPENSE,
                InterconnectionStatus.NOT_SENT, PERIOD_TO.plusSeconds(86400 * 400), null);
        flush();

        assertEquals(2, search(filter(null, null, null)).getTotalElements());
    }

    @Test
    void resultsAreOrderedByPrescribedAtDescending() {
        persistPrescription("RX000009", PrescriptionStatus.PENDING_DISPENSE,
                InterconnectionStatus.NOT_SENT, PERIOD_FROM.plusSeconds(100), null);
        persistPrescription("RX000010", PrescriptionStatus.PENDING_DISPENSE,
                InterconnectionStatus.NOT_SENT, PERIOD_FROM.plusSeconds(300), null);
        persistPrescription("RX000011", PrescriptionStatus.PENDING_DISPENSE,
                InterconnectionStatus.NOT_SENT, PERIOD_FROM.plusSeconds(200), null);
        flush();

        List<String> codes = search(filter(PERIOD_FROM, PERIOD_TO, null)).getContent().stream()
                .map(PrescriptionReconciliationItemResult::prescriptionCode)
                .toList();

        assertEquals(List.of("RX000010", "RX000011", "RX000009"), codes);
    }

    @Test
    void identicalTimestampsAreTieBrokenByIdDescending() {
        Instant sameInstant = PERIOD_FROM.plusSeconds(500);
        persistPrescription("RX000012", PrescriptionStatus.PENDING_DISPENSE,
                InterconnectionStatus.NOT_SENT, sameInstant, null);
        persistPrescription("RX000013", PrescriptionStatus.PENDING_DISPENSE,
                InterconnectionStatus.NOT_SENT, sameInstant, null);
        flush();

        List<UUID> ids = search(filter(PERIOD_FROM, PERIOD_TO, null)).getContent().stream()
                .map(PrescriptionReconciliationItemResult::prescriptionId)
                .toList();

        assertEquals(2, ids.size());
        assertTrue(compareUnsignedDescending(ids.get(0), ids.get(1)),
                "expected id descending tie break using BINARY(16) unsigned byte ordering");
    }

    /**
     * Ids are stored as BINARY(16) and ordered by the database with unsigned byte comparison,
     * which is not the same as UUID.compareTo (signed long comparison). This mirrors the
     * database semantics so the deterministic tie break is actually verified.
     */
    private static boolean compareUnsignedDescending(UUID left, UUID right) {
        byte[] leftBytes = toBytes(left);
        byte[] rightBytes = toBytes(right);
        for (int index = 0; index < leftBytes.length; index++) {
            int leftUnsigned = leftBytes[index] & 0xFF;
            int rightUnsigned = rightBytes[index] & 0xFF;
            if (leftUnsigned != rightUnsigned) {
                return leftUnsigned > rightUnsigned;
            }
        }
        return false;
    }

    private static byte[] toBytes(UUID value) {
        java.nio.ByteBuffer buffer = java.nio.ByteBuffer.allocate(16);
        buffer.putLong(value.getMostSignificantBits());
        buffer.putLong(value.getLeastSignificantBits());
        return buffer.array();
    }

    @Test
    void prescriptionCodeFilterIsExact() {
        persistPrescription("RX000014", PrescriptionStatus.PENDING_DISPENSE,
                InterconnectionStatus.NOT_SENT, PERIOD_FROM.plusSeconds(50), null);
        persistPrescription("RX000015", PrescriptionStatus.PENDING_DISPENSE,
                InterconnectionStatus.NOT_SENT, PERIOD_FROM.plusSeconds(60), null);
        flush();

        Page<PrescriptionReconciliationItemResult> page = search(
                filter(null, null, "RX000014"));

        assertEquals(1, page.getTotalElements());
        assertEquals("RX000014", page.getContent().get(0).prescriptionCode());
    }

    @Test
    void outcomeFilterRestrictsToTheRequestedGroup() {
        persistPrescription("RX000016", PrescriptionStatus.DISPENSED,
                InterconnectionStatus.FAILED, PERIOD_FROM.plusSeconds(70), PERIOD_FROM.plusSeconds(80));
        persistPrescription("RX000017", PrescriptionStatus.PENDING_DISPENSE,
                InterconnectionStatus.SUCCESS, PERIOD_FROM.plusSeconds(90), PERIOD_FROM.plusSeconds(95));
        flush();

        Page<PrescriptionReconciliationItemResult> page = search(filter(
                PERIOD_FROM, PERIOD_TO, null,
                new ReconciliationOutcomeGroup(
                        List.of(PrescriptionStatus.PENDING_DISPENSE),
                        List.of(InterconnectionStatus.SUCCESS))));

        assertEquals(1, page.getTotalElements());
        assertEquals("RX000017", page.getContent().get(0).prescriptionCode());
    }

    @Test
    void twoGroupsActAsOrAndReturnBothDiscrepancyCategories() {
        persistPrescription("RX000018", PrescriptionStatus.DISPENSED,
                InterconnectionStatus.FAILED, PERIOD_FROM.plusSeconds(110), PERIOD_FROM.plusSeconds(120));
        persistPrescription("RX000019", PrescriptionStatus.PENDING_DISPENSE,
                InterconnectionStatus.SUCCESS, PERIOD_FROM.plusSeconds(130), PERIOD_FROM.plusSeconds(140));
        persistPrescription("RX000020", PrescriptionStatus.DISPENSED,
                InterconnectionStatus.SUCCESS, PERIOD_FROM.plusSeconds(150), PERIOD_FROM.plusSeconds(160));
        persistPrescription("RX000021", PrescriptionStatus.CANCELLED,
                InterconnectionStatus.NOT_SENT, PERIOD_FROM.plusSeconds(170), null);
        flush();

        Page<PrescriptionReconciliationItemResult> page = search(filter(
                PERIOD_FROM, PERIOD_TO, null,
                new ReconciliationOutcomeGroup(
                        List.of(PrescriptionStatus.PENDING_DISPENSE),
                        List.of(InterconnectionStatus.SUCCESS)),
                new ReconciliationOutcomeGroup(
                        List.of(PrescriptionStatus.DISPENSED, PrescriptionStatus.PARTIALLY_DISPENSED),
                        List.of(InterconnectionStatus.NOT_SENT, InterconnectionStatus.FAILED))));

        assertEquals(2, page.getTotalElements());
        assertTrue(page.getContent().stream().allMatch(PrescriptionReconciliationItemResult::discrepancy));
    }

    @Test
    void countMatchesRowsForEveryFilterShape() {
        persistPrescription("RX000022", PrescriptionStatus.DISPENSED,
                InterconnectionStatus.FAILED, PERIOD_FROM.plusSeconds(200), PERIOD_FROM.plusSeconds(210));
        persistPrescription("RX000023", PrescriptionStatus.PENDING_DISPENSE,
                InterconnectionStatus.SUCCESS, PERIOD_FROM.plusSeconds(220), PERIOD_FROM.plusSeconds(230));
        flush();

        Page<PrescriptionReconciliationItemResult> unfiltered = search(
                filter(PERIOD_FROM, PERIOD_TO, null));
        Page<PrescriptionReconciliationItemResult> byOutcome = search(filter(
                PERIOD_FROM, PERIOD_TO, null,
                new ReconciliationOutcomeGroup(
                        List.of(PrescriptionStatus.DISPENSED),
                        List.of(InterconnectionStatus.FAILED))));
        Page<PrescriptionReconciliationItemResult> byCode = search(
                filter(PERIOD_FROM, PERIOD_TO, "RX000022"));

        assertEquals(2, unfiltered.getTotalElements());
        assertEquals(2, unfiltered.getContent().size());
        assertEquals(1, byOutcome.getTotalElements());
        assertEquals(1, byOutcome.getContent().size());
        assertEquals(1, byCode.getTotalElements());
        assertEquals(1, byCode.getContent().size());
    }

    @Test
    void cancelledRowsStayVisibleAndOutsideTheTwoDiscrepancyCategories() {
        persistPrescription("RX000024", PrescriptionStatus.CANCELLED,
                InterconnectionStatus.SUCCESS, PERIOD_FROM.plusSeconds(300), PERIOD_FROM.plusSeconds(310));
        flush();

        Page<PrescriptionReconciliationItemResult> page = search(
                filter(PERIOD_FROM, PERIOD_TO, null));

        assertEquals(1, page.getTotalElements());
        assertEquals(PrescriptionReconciliationOutcome.CANCELLED, page.getContent().get(0).outcome());
        assertFalse(page.getContent().get(0).discrepancy());
        assertFalse(page.getContent().get(0).retransmissionEligible());
    }

    @Test
    void batchedDispenseAggregateFillsTheLatestDispensingInstant() {
        UUID id = persistPrescription("RX000025", PrescriptionStatus.PARTIALLY_DISPENSED,
                InterconnectionStatus.SUCCESS, PERIOD_FROM.plusSeconds(400), null);
        Instant firstDispense = PERIOD_FROM.plusSeconds(410);
        Instant secondDispense = PERIOD_FROM.plusSeconds(420);
        persistDispense(id, firstDispense);
        persistDispense(id, secondDispense);
        flush();

        PrescriptionReconciliationItemResult row = search(filter(PERIOD_FROM, PERIOD_TO, null))
                .getContent().get(0);

        assertEquals(secondDispense, row.lastDispensedAt());
        assertEquals(PrescriptionReconciliationOutcome.CONSISTENT, row.outcome());
        assertFalse(row.discrepancy());
    }

    @Test
    void reconciliationNoteCountIsFilledFromTheBatchedCount() {
        UUID id = persistPrescription("RX000026", PrescriptionStatus.DISPENSED,
                InterconnectionStatus.FAILED, PERIOD_FROM.plusSeconds(500), PERIOD_FROM.plusSeconds(510));
        for (int index = 0; index < 3; index++) {
            entityManager.persist(PrescriptionReconciliationNoteEntity.builder()
                    .id(UUID.randomUUID())
                    .prescriptionId(id)
                    .reconciliationOutcome(PrescriptionReconciliationOutcome.DISPENSED_NOT_TRANSMITTED)
                    .reason("ly do " + index)
                    .notedBy(UUID.randomUUID())
                    .notedAt(PERIOD_FROM.plusSeconds(520 + index))
                    .createdAt(PERIOD_FROM.plusSeconds(520 + index))
                    .build());
        }
        flush();

        PrescriptionReconciliationItemResult row = search(filter(PERIOD_FROM, PERIOD_TO, null))
                .getContent().get(0);

        assertEquals(3L, row.reconciliationNoteCount());
    }

    @Test
    void emptyPeriodReturnsEmptyPage() {
        Page<PrescriptionReconciliationItemResult> page = search(
                filter(Instant.parse("2020-01-01T00:00:00Z"), Instant.parse("2020-02-01T00:00:00Z"), null));

        assertTrue(page.getContent().isEmpty());
        assertEquals(0, page.getTotalElements());
    }

    @Test
    void zeroOutcomeGroupsBehaveLikeNoOutcomeFilter() {
        persistPrescription("RX000027", PrescriptionStatus.PENDING_DISPENSE,
                InterconnectionStatus.SUCCESS, PERIOD_FROM.plusSeconds(10), PERIOD_FROM.plusSeconds(20));
        persistPrescription("RX000028", PrescriptionStatus.CANCELLED,
                InterconnectionStatus.NOT_SENT, PERIOD_FROM.plusSeconds(30), null);
        flush();

        Page<PrescriptionReconciliationItemResult> page = search(filter(PERIOD_FROM, PERIOD_TO, null));

        assertEquals(2, page.getTotalElements());
        assertEquals(2, page.getContent().size());
    }

    @Test
    void oneOutcomeGroupKeepsTheExactCrossProductSemantics() {
        persistPrescription("RX000033", PrescriptionStatus.DISPENSED,
                InterconnectionStatus.SUCCESS, PERIOD_FROM.plusSeconds(40), PERIOD_FROM.plusSeconds(45));
        persistPrescription("RX000034", PrescriptionStatus.PARTIALLY_DISPENSED,
                InterconnectionStatus.SUCCESS, PERIOD_FROM.plusSeconds(50), PERIOD_FROM.plusSeconds(55));
        persistPrescription("RX000035", PrescriptionStatus.DISPENSED,
                InterconnectionStatus.FAILED, PERIOD_FROM.plusSeconds(60), PERIOD_FROM.plusSeconds(65));
        flush();

        Page<PrescriptionReconciliationItemResult> page = search(filter(
                PERIOD_FROM, PERIOD_TO, null,
                new ReconciliationOutcomeGroup(
                        List.of(PrescriptionStatus.DISPENSED, PrescriptionStatus.PARTIALLY_DISPENSED),
                        List.of(InterconnectionStatus.SUCCESS))));

        assertEquals(2, page.getTotalElements());
        assertTrue(page.getContent().stream()
                .allMatch(row -> row.outcome() == PrescriptionReconciliationOutcome.CONSISTENT));
    }

    @Test
    void threeOutcomeGroupsAreRepresentedWithoutAnArtificialMaximum() {
        persistPrescription("RX000029", PrescriptionStatus.PENDING_DISPENSE,
                InterconnectionStatus.SUCCESS, PERIOD_FROM.plusSeconds(40), PERIOD_FROM.plusSeconds(50));
        persistPrescription("RX000030", PrescriptionStatus.DISPENSED,
                InterconnectionStatus.FAILED, PERIOD_FROM.plusSeconds(60), PERIOD_FROM.plusSeconds(70));
        persistPrescription("RX000031", PrescriptionStatus.CANCELLED,
                InterconnectionStatus.NOT_SENT, PERIOD_FROM.plusSeconds(80), null);
        persistPrescription("RX000032", PrescriptionStatus.DISPENSED,
                InterconnectionStatus.SUCCESS, PERIOD_FROM.plusSeconds(90), PERIOD_FROM.plusSeconds(95));
        flush();

        Page<PrescriptionReconciliationItemResult> page = search(filter(
                PERIOD_FROM, PERIOD_TO, null,
                new ReconciliationOutcomeGroup(
                        List.of(PrescriptionStatus.PENDING_DISPENSE),
                        List.of(InterconnectionStatus.SUCCESS)),
                new ReconciliationOutcomeGroup(
                        List.of(PrescriptionStatus.DISPENSED),
                        List.of(InterconnectionStatus.FAILED)),
                new ReconciliationOutcomeGroup(
                        List.of(PrescriptionStatus.CANCELLED),
                        List.of(InterconnectionStatus.NOT_SENT))));

        assertEquals(3, page.getTotalElements());
        assertEquals(
                List.of("RX000031", "RX000030", "RX000029"),
                page.getContent().stream()
                        .map(PrescriptionReconciliationItemResult::prescriptionCode)
                        .toList());
    }

    @Test
    void paginationTotalsAreCorrectAcrossEveryPage() {
        for (int index = 0; index < 5; index++) {
            persistPrescription("RX00004" + index, PrescriptionStatus.PENDING_DISPENSE,
                    InterconnectionStatus.NOT_SENT, PERIOD_FROM.plusSeconds(100 + index), null);
        }
        flush();

        ReconciliationQueryFilter filter = filter(PERIOD_FROM, PERIOD_TO, null);
        Page<PrescriptionReconciliationItemResult> first =
                adapter.findByFilter(filter, PageRequest.of(0, 2));
        Page<PrescriptionReconciliationItemResult> second =
                adapter.findByFilter(filter, PageRequest.of(1, 2));
        Page<PrescriptionReconciliationItemResult> third =
                adapter.findByFilter(filter, PageRequest.of(2, 2));

        assertEquals(5, first.getTotalElements());
        assertEquals(3, first.getTotalPages());
        assertEquals(2, first.getContent().size());
        assertEquals(2, second.getContent().size());
        assertEquals(1, third.getContent().size());
        assertEquals(5, second.getTotalElements());
        assertEquals(5, third.getTotalElements());

        Page<PrescriptionReconciliationItemResult> byCode = adapter.findByFilter(
                filter(PERIOD_FROM, PERIOD_TO, "RX000043"), PageRequest.of(0, 2));

        assertEquals(1, byCode.getTotalElements());
        assertEquals(1, byCode.getContent().size());
        assertEquals("RX000043", byCode.getContent().get(0).prescriptionCode());
    }
}
