package com.benhsoan.exception;

import org.springframework.http.HttpStatus;

import com.benhsoan.domain.shared.exception.DomainErrorCode;

final class DomainExceptionHttpStatusMapper {

    private DomainExceptionHttpStatusMapper() {
    }

    static HttpStatus statusFor(DomainErrorCode code) {
        return switch (code) {
            case APPOINTMENT_NOT_FOUND,
                    APPOINTMENT_SERIES_NOT_FOUND,
                    BACKUP_NOT_FOUND,
                    BATCH_NOT_FOUND,
                    CARE_LOG_NOT_FOUND,
                    CASHIER_SHIFT_NOT_FOUND,
                    CLINICAL_ATTACHMENT_NOT_FOUND,
                    CLINICAL_ORDER_NOT_FOUND,
                    CLINICAL_ORDER_ITEM_NOT_FOUND,
                    CLINICAL_REFERENCE_RANGE_NOT_FOUND,
                    CLINICAL_RESULT_NOT_FOUND,
                    CLINICAL_SERVICE_CATALOG_NOT_FOUND,
                    DIAGNOSIS_CATALOG_NOT_FOUND,
                    DOCTOR_NOT_FOUND,
                    DOCTOR_TIMEOFF_NOT_FOUND,
                    DRUG_INTERACTION_NOT_FOUND,
                    FOLLOW_UP_REMINDER_NOT_FOUND,
                    INVOICE_NOT_FOUND,
                    DISCOUNT_REQUEST_NOT_FOUND,
                    MEDICAL_RECORD_NOT_FOUND,
                    MEDICAL_RECORD_TEMPLATE_NOT_FOUND,
                    MEDICINE_NOT_FOUND,
                    PATIENT_ALLERGY_NOT_FOUND,
                    PATIENT_CHRONIC_DISEASE_NOT_FOUND,
                    PATIENT_FAMILY_HISTORY_NOT_FOUND,
                    PATIENT_NOT_FOUND,
                    PATIENT_IMPORT_LOG_NOT_FOUND,
                    PATIENT_PORTAL_NOTIFICATION_NOT_FOUND,
                    PAYMENT_NOT_FOUND,
                    PORTAL_LOOKUP_NOT_FOUND,
                    PRESCRIPTION_ITEM_NOT_FOUND,
                    PRESCRIPTION_NOT_FOUND,
                    QUEUE_ITEM_NOT_FOUND,
                    QUEUE_NOT_FOUND,
                    ROLE_NOT_FOUND,
                    ROOM_NOT_FOUND,
                    SECURITY_ALERT_NOT_FOUND,
                    SERVICE_CATALOG_NOT_FOUND,
                    SPECIALTY_NOT_FOUND,
                    USER_NOT_FOUND,
                    VISIT_NOT_FOUND,
                    VITAL_SIGN_NOT_FOUND,
                    WAITLIST_ENTRY_NOT_FOUND -> HttpStatus.NOT_FOUND;
            case ACCOUNT_DISABLED,
                    ACCOUNT_LOCKED,
                    DOCTOR_INACTIVE,
                    INVOICE_UNAUTHORIZED_ADJUSTMENT,
                    SELF_APPROVAL_NOT_ALLOWED,
                    MEDICAL_RECORD_ACCESS_DENIED,
                    MEDICAL_RECORD_UNAUTHORIZED_RECIPIENT,
                    MEDICAL_RECORD_UNAUTHORIZED_SIGNER,
                    MUST_CHANGE_PASSWORD,
                    PATIENT_CONSENT_ACCESS_DENIED,
                    PATIENT_INACTIVE,
                    UNAUTHORIZED_APPOINTMENT_OPERATION,
                    UNAUTHORIZED_PRESCRIPTION_AMENDMENT,
                    UNAUTHORIZED_PRESCRIPTION_CANCELLATION,
                    UNAUTHORIZED_QUEUE_OPERATION,
                    VISIT_ENCOUNTER_ACCESS_DENIED,
                    CASHIER_SHIFT_SELF_CONFIRMATION_NOT_ALLOWED -> HttpStatus.FORBIDDEN;
            case INVALID_CREDENTIALS,
                    SESSION_EXPIRED,
                    TEMP_PASSWORD_EXPIRED,
                    TOKEN_INVALID,
                    TWO_FACTOR_CHALLENGE_INVALID -> HttpStatus.UNAUTHORIZED;
            case APPOINTMENT_NOT_OVERDUE,
                    APPOINTMENT_PAST_CUTOFF,
                    APPOINTMENT_TIME_IN_PAST,
                    BATCH_ALREADY_DISCARDED,
                    BATCH_NOT_EXPIRED,
                    DOCTOR_SCHEDULE_UNAVAILABLE,
                    DOCTOR_NOT_WORKING,
                    INVALID_BACKUP_STATUS,
                    INVALID_DOCTOR_ROLE,
                    INVALID_OLD_PASSWORD,
                    INVALID_VERIFICATION_CODE,
                    MEDICAL_RECORD_MISSING_AUTHORIZATION,
                    MEDICAL_RECORD_MISSING_DIAGNOSIS,
                    MEDICAL_RECORD_NOT_LOCKED,
                    MEDICAL_RECORD_NOT_OVERDUE,
                    MEDICAL_RECORD_NOT_SIGNED,
                    PATIENT_CONSENT_REQUIRED,
                    CANNOT_MERGE_SAME_PATIENT,
                    PAYMENT_AMOUNT_MISMATCH,
                    DISCOUNT_EXCEEDS_TOTAL,
                    PRESCRIPTION_NO_CHANGES,
                    SAME_PASSWORD_NOT_ALLOWED,
                    SELF_DRUG_INTERACTION,
                    VALIDATION_FAILED,
                    VERIFICATION_CODE_EXPIRED,
                    CANNOT_DEACTIVATE_DEFAULT_SPECIALTY,
                    NO_UNSETTLED_PAYMENTS,
                    CASHIER_SHIFT_NOTE_REQUIRED,
                    DOCTOR_HAS_AVAILABLE_SLOTS,
                    WAITLIST_INVALID_STATUS,
                    WEAK_PASSWORD -> HttpStatus.BAD_REQUEST;
            case ALLERGY_CONFIRMATION_REQUIRED,
                    APPOINTMENT_ALREADY_CANCELLED,
                    APPOINTMENT_ALREADY_COMPLETED,
                    APPOINTMENT_ALREADY_IN_PROGRESS,
                    APPOINTMENT_INVALID_STATUS,
                    APPOINTMENT_SERIES_CONFLICT,
                    APPOINTMENT_TIME_CONFLICT,
                    BATCH_STATE_CONFLICT,
                    CASHIER_SHIFT_ALREADY_CONFIRMED,
                    PAYMENT_ALREADY_SETTLED,
                    CHECK_IN_CONFLICT,
                    CLINICAL_ORDER_ALREADY_CANCELLED,
                    CLINICAL_ORDER_ALREADY_COMPLETED,
                    CLINICAL_ORDER_HAS_RESULT,
                    CLINICAL_ORDER_INVALID_STATUS,
                    CLINICAL_ORDER_INVALID_VISIT,
                    CLINICAL_ORDER_ITEM_INVALID_STATUS,
                    CLINICAL_ORDER_LOCKED_MEDICAL_RECORD,
                    PENDING_CLINICAL_ORDERS_WARNING,
                    CLINICAL_REFERENCE_RANGE_OVERLAP,
                    CLINICAL_RESULT_ALREADY_FINALIZED,
                    CLINICAL_RESULT_INVALID_STATUS,
                    CLINICAL_SERVICE_CODE_ALREADY_EXISTS,
                    CLINICAL_SERVICE_UNAVAILABLE,
                    CONCURRENT_IMPORT_IN_PROGRESS,
                    CONTRAINDICATION_CONFIRMATION_REQUIRED,
                    CONTROLLED_MEDICINE_CONFIRMATION_REQUIRED,
                    DIAGNOSIS_CATALOG_CODE_ALREADY_EXISTS,
                    DIAGNOSIS_CATALOG_DELETE_NOT_ALLOWED,
                    DIAGNOSIS_CATALOG_IN_USE,
                    DOCTOR_NOT_ASSIGNED_TO_ROOM,
                    DOCTOR_ROOM_ASSIGNMENT_CONFLICT,
                    DOCTOR_TIMEOFF_CONFLICT,
                    DRUG_INTERACTION_ALREADY_EXISTS,
                    EMAIL_ALREADY_EXISTS,
                    FOLLOW_UP_REMINDER_INVALID_STATUS,
                    INSUFFICIENT_STOCK,
                    INTERACTION_CONFIRMATION_REQUIRED,
                    INVOICE_ALREADY_ISSUED,
                    PENDING_DISCOUNT_APPROVAL,
                    INVALID_DISCOUNT_STATE,
                    DISCOUNT_ALREADY_EXISTS,
                    LAST_ADMINISTRATOR_PERMISSION,
                    MEDICAL_RECORD_ALREADY_EXISTS_FOR_VISIT,
                    MEDICAL_RECORD_AMENDMENT_REQUIRES_COMPLETED_VISIT,
                    MEDICAL_RECORD_INVALID_STATUS,
                    MEDICAL_RECORD_INVALID_VISIT,
                    MEDICAL_RECORD_IN_RETENTION_PERIOD,
                    PATIENT_ALREADY_IN_WAITLIST,
                    MEDICAL_RECORD_LOCKED,
                    MEDICAL_RECORD_TEMPLATE_CHANGE_WITH_CONTENT,
                    MEDICAL_RECORD_TEMPLATE_DEFAULT_NOT_CONFIGURED,
                    MEDICAL_RECORD_TEMPLATE_DEFAULT_REPLACEMENT_REQUIRED,
                    MEDICAL_RECORD_TEMPLATE_INACTIVE,
                    MEDICAL_RECORD_TEMPLATE_INVALID_REPLACEMENT,
                    MEDICAL_RECORD_TEMPLATE_LAST_ACTIVE,
                    MEDICAL_RECORD_TEMPLATE_NAME_DUPLICATE,
                    MEDICAL_RECORD_TEMPLATE_SPECIALTY_MISMATCH,
                    SPECIALTY_CODE_ALREADY_EXISTS,
                    SPECIALTY_IN_USE,
                    SPECIALTY_NAME_ALREADY_EXISTS,
                    MEDICATION_RETURN_PAYMENT_NOT_REFUNDED,
                    MEDICINE_CODE_ALREADY_EXISTS,
                    MEDICINE_INACTIVE,
                    PATIENT_ALREADY_EXISTS,
                    PATIENT_ALREADY_MERGED,
                    PATIENT_IDENTITY_CONFLICT,
                    PATIENT_ALLERGY_ALREADY_EXISTS,
                    PATIENT_CHRONIC_DISEASE_ALREADY_EXISTS,
                    PAYMENT_ALREADY_EXISTS,
                    PAYMENT_NOT_ALLOWED,
                    PAYMENT_REQUIRED_FOR_INVOICE,
                    PHONE_ALREADY_EXISTS,
                    PRESCRIPTION_ALREADY_CANCELLED,
                    PRESCRIPTION_ALREADY_DISPENSED,
                    PRESCRIPTION_CLINICAL_CONTEXT_CONFLICT,
                    PRESCRIPTION_INVALID_STATUS,
                    PRESCRIPTION_NOT_PRINTABLE,
                    QUEUE_ITEM_INVALID_STATUS,
                    ROOM_CODE_ALREADY_EXISTS,
                    USER_ALREADY_EXISTS,
                    VISIT_ALREADY_CANCELLED,
                    VISIT_ALREADY_COMPLETED,
                    VISIT_INVALID_STATUS -> HttpStatus.CONFLICT;
            case BACKUP_EXECUTION_FAILED -> HttpStatus.INTERNAL_SERVER_ERROR;
            case REPORT_DATA_EMPTY,
                    CONTRAINDICATION_DATA_MISSING -> HttpStatus.UNPROCESSABLE_ENTITY;
            case TOO_MANY_LOGIN_ATTEMPTS,
                    VERIFICATION_CODE_COOLDOWN -> HttpStatus.TOO_MANY_REQUESTS;
            default -> HttpStatus.BAD_REQUEST;
        };
    }
}
